# Generated by Django 5.2.3 on 2025-07-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
